### ISSUE TITLE
Output issue

### ISSUE THREAD

**Issue by Mossesval** [glavrentiadis/NonErgodicGMM_public#1]
I 've tried to run stan_BA18_f1.00hz_NGAWest2CA_compute_coeffs and i don't have the ../output/NergEASGMM_f1.00hz file 
this is the cmd error ''FileNotFoundError: [Errno 2] No such file or directory: '../../data/output/NergEASGMM_f1.00hz/NergEASGMM_f1.00hz_NGAWestCA_laten_var_unbound_hyp_stan_posterior.csv''

**Comment by glavrentiadis** [comment]
Did you first run stan_BA18_f1.00hz_NGAWest2CA_unbounded_hyp.py to estimate the coefficients at the known locations? stan_BA18_f1.00hz_NGAWest2CA_compute_coeffs.py computes the non-ergodic coefficients at the new locations based on the coefficients at the existing locations. I will write an instructions document to explain what each function does.

**Comment by LIUMJ-gif** [comment]
The file ’stan_BA18_f1.00hz_NGAWest2CA_unbounded_hyp.py‘ didn't find it

**Comment by glavrentiadis** [comment]
I apologize for this, I uploaded stan_BA18_f1.00hz_NGAWest2CA_unbounded_hyp.py
Please let me know if any issue persists

**Comment by glavrentiadis** [comment]
Added `instructions.Rmd` which contain brief instructions on running the two scripts.
