### ISSUE TITLE
Regarding the issue of "stan_BA18_f1.00hz-NGAWest2CA-compute-coeffs. py"

### ISSUE THREAD

**Issue by LIUMJ-gif** [glavrentiadis/NonErgodicGMM_public#2]
The output file of program "stan_BA18_f1.00hz-NGAWest2CA_unbound_hyp. py" does not match the program "stan_BA18_f1.00hz-NGAWest2CA compute coeffs. py", and the index in the latter is inconsistent with the header of the former's output file. 
Do we need to modify the index of the latter separately

**Comment by glavrentiadis** [comment]
Thank you for identifying this issue. Could you please elaborate on which indices are causing the issue?

**Comment by LIUMJ-gif** [comment]
Thank you for your reply. I have modified some relevant indexes according to the header of the generated file and have successfully run them.

**Comment by glavrentiadis** [comment]
Thank you independently I also fixed the issue on the indexes and pushed a new version of stan_BA18_f1.00hz_NGAWest2CA_compute_coeffs.py on Git Hub that should be available for future applications.
